### ISSUE TITLE
Question: Is it possible to get results as an associative array ?

### ISSUE THREAD

**Issue by liteultom** [thecodingmachine/tdbm#158]
Hi !

I'm using TDBM on a project, is it possible to get a result as an associative array ( [see here for the same thing in doctrine](https://stackoverflow.com/questions/7259256/how-to-get-a-doctrine2-result-object-as-an-associative-array) ) instead of a full instance of an object ?

**Comment by moufmouf** [comment]
Hey @liteultom ,

Currently, it is not possible to perform a partial query (i.e. fetch only a few columns of an object) instead of all the columns and build the complete object.

So right now, you have to fetch the objects (using the `findXXX` methods) and then cast it as an array (the easy pick is the `jsonSerialize` method available on all beans that will turn your object in an array).

That being said, we do have plans to work on objects built from partial queries (queries that do not return all the fields) in TDBM 5.2.

Out of curiosity, are you asking the question because you are having performance issues or is it because you are looking for a better developer experience?

**Comment by liteultom** [comment]
Hi !

Thank you for your answer. I'm asking the question in anticipation of performance issue, because I want to compute statistics on a large number of large objects. With array hydration I would only need to pick 2 or 3 fields per object to compute my statistics instead of having TDBM build a full instance for each of this large object which I will fetch by thousands, this is why I was asking if this was possible.

**Comment by moufmouf** [comment]
Ok! We will be working on this in TDBM 5.2.

In the meantime, if you want to benefit from the same features provided by TDBM (like the automatic join and the automatic discarding of null parameter), while doing a pure SQL query, you can use [Magic Query](https://github.com/thecodingmachine/magic-query) directly.

Magic Query is the library used by TDBM to make the SQL queries. It might be a good solution for your problem, and it will give you an associative array for a result.

**Comment by liteultom** [comment]
Thank you for the tips :)
