### ISSUE TITLE
DaoFactory performance issues with Mouf framework (5.0.16)

### ISSUE THREAD

**Issue by WizMik** [thecodingmachine/tdbm#169]
Hello !

I was told that injecting DaoFactory is somehow deprecated because it causes performance issues (when injecting, all DAOs are loaded or someting) !
I don't know it it's related to Mouf or TDBM, but its a shame ! DaoFactory is really convenient and it would be really nice to keep using it, since its generated !

Thanks

**Comment by moufmouf** [comment]
Ok. 2 things here:

- You should indeed avoid using `DaoFactory` as much as possible. When a controller or a service depends on DaoFactory, it means it depends potentially on any table in the data model. If you only inject the required DAOs, you know (just by looking at the constructor's signature) what tables are used. So it's a good practice to depend on the minimum possible dependencies

- Regarding DAOFactory performance, it was indeed bad until TDBM 5.1 because the DaoFactory had to instantiate all the DAOs. In TDBM 5.1, the DAOs are instantiated on the fly from the container. It means that:
    - you must inject the container in the DaoFactory.
    - you no longer have performance problems.

So starting with TDBM 5.1, you can use the DaoFactory without any performance impact... but I would still consider it a bad practice :)

**Comment by WizMik** [comment]
Got it ! Thanks :D !
